### ISSUE TITLE
Change graphql domain and port

### ISSUE THREAD

**Issue by murillio4** [jamesmacaulay/elm-graphql#26]
Hi! Is it possible to change doman and port to the graphql server that the package will use? I've tried to change the url with `RequestOptions` but it seems to only be able to edit the query and not the domain name and port.

**Comment by jamesmacaulay** [comment]
You should be able to supply a fully qualified URL for the `url` field which includes the scheme + domain + port (e.g. “https://example.com:8000/graphql”) instead of only the path. Note that the server must support CORS for the request to work cross-domain. All this should work the same as if you were using the `elm-lang/http` package directly.

If you have CORS working correctly on the server and supplying the fully qualified URL doesn’t work, then there’s something else wrong and I can help debug further. Let me know.
