### ISSUE TITLE
Feature Request: DSL

### ISSUE THREAD

**Issue by anagrius** [jamesmacaulay/elm-graphql#29]
Hi James,

Please take this issue in the spirit it was written - as constructive feedback.
I have been using Elm-GraphQL for a few weeks now and I am sorry to say that I really find the
query builders hard to use, and difficult to read compared the raw queries themselves in GraphQL format.

I think the problem is that the syntax is quite far removed from GraphQL. The success of elm-lang/html largely comes from the fact that people almost don't have to learn any new concepts e.g. anchor tag is still JUST `a`, and `onClick` is `onClick`.

I think it would be a good idea to implement a DSL ala elm-lang/html for Elm-GraphQL.

I haven't spent alot of time thinking about the format, but to give you an idea of what I am talking about it would be something along the lines of:

```Elm
query [
  taggedField MyTagFoo "viewer" (selection [(myArg 1), (id "123")] [
    field "name"
    field "height"
  ]),
  taggedField MyTagBar "viewer" (selection [(myArg 2)] [
    field "name"
    field "age"
  ])
]
```
If you find this interesting I would love to help figuring out how to build this, maybe on top of your builders.

**Comment by dillonkearns** [comment]
@anagrius I just wanted to point out that using a list here wouldn't allow you to build up the decoder.  The compiler loses some type information when you build it up into a list (the compiler doesn't know whether a list contains 0 items or 3, and they must all have the same type). A good place to look for inspiration for a DSL would be the [json-decode](package.elm-lang.org/packages/elm-lang/core/5.1.1/Json-Decode) and [json-decode-pipeline](package.elm-lang.org/packages/NoRedInk/elm-decode-pipeline/latest) packages, since they also build up decoders where the compiler is incrementally building up types. I hope that helps!

**Comment by anagrius** [comment]
@dillonkearns Sure thanks. I just want to get a dialog about what is possible and how we could solve it in an elegant way. 👍

**Comment by dillonkearns** [comment]
Absolutely, I think it's a great discussion. Just wanted to point that out to help make sure it's as productive as possible 👍

**Comment by jamesmacaulay** [comment]
@anagrius Sorry for the delayed response, I haven't been very active with this project this month. I understand where you're coming from about the difficulty of using the query builder DSL. Unfortunately, as hinted at by @dillonkearns in his comment, a lot of the complexity of the interface is inherent to the problem of trying to build up a JSON decoder along with the representation of the query document.

There were of course various choices and trade-offs I made along the way in designing the current DSL, and some of those choices added slightly to the complexity for the sake of having better type-safety. But if you want to keep the requirement of building up decoders automatically, then there's only so much you can do.

Because of this, I don't have any plans for overhauling the DSL. Instead, I think a better place to put development effort for improving the user experience is in generating Elm code from GraphQL query documents:

https://github.com/jamesmacaulay/elm-graphql/issues/25

This isn't a trivial task, so I'm not sure when it'll be done. In the meantime, if you want a simpler DSL like the one you describe *and* you don't mind writing separate decoders, there's this other GraphQL package:

http://package.elm-lang.org/packages/ghivert/elm-graphql/latest

And if you want to write queries in GraphQL and generate Elm code from that right now, there's this project which kind of died a while ago and didn't work in recent versions of Elm but people have forked it and maybe it works now:

https://github.com/Blissfully/elm-graphql

**Comment by jamesmacaulay** [comment]
Also @dillonkearns released this package recently which generates a nice DSL from a GraphQL schema:

http://package.elm-lang.org/packages/dillonkearns/graphqelm/latest

**Comment by jamesmacaulay** [comment]
I'm going to close this issue for the reasons described above, but if you want to try your hand at making a better DSL then I don't want to discourage you — it was a great learning experience for me and a lot of fun :) You could either fork this project and write a new `...Builder` module from scratch, or perhaps build something on top of my DSL that suits your tastes better.
